import { createHmac, timingSafeEqual } from 'node:crypto';
import { createReadStream } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { FastifyPluginAsync } from 'fastify';
import { contentDisposition, type StorageService } from './storage.js';

/**
 * Development and CI only (env.ts refuses it in production): files on local disk, served by
 * the API itself through signed, expiring URLs that behave like B2's presigned ones (exact
 * type and size on PUT, chosen disposition on GET). Lets E2E tests run without B2. Production
 * never proxies file bytes through the API (CLAUDE.md).
 */
// The grant travels in the query (too long for a path parameter); request logs drop queries
export const LOCAL_STORAGE_PATH = '/local-storage';

type Grant =
  | { op: 'put'; key: string; type: string; size: number; exp: number }
  | { op: 'get'; key: string; exp: number; disposition: string; type?: string };

// Keys are generated by the API (uploads/<user>/<id>, documents/<id>); refuse anything else
const SAFE_KEY = /^(uploads|documents)(\/[0-9a-f-]{36}){1,2}$/;

export interface LocalStorageConfig {
  dir: string;
  /** Origin the browser reaches the API on, e.g. http://localhost:3000 */
  publicUrl: string;
  secret: string;
}

export function createLocalStorage(config: LocalStorageConfig): {
  storage: StorageService;
  routes: FastifyPluginAsync;
} {
  const sign = (body: string) =>
    createHmac('sha256', config.secret).update(body).digest('base64url');
  const issue = (grant: Grant) => {
    const body = Buffer.from(JSON.stringify(grant)).toString('base64url');
    return `${config.publicUrl}${LOCAL_STORAGE_PATH}?t=${body}.${sign(body)}`;
  };
  const verify = (token: string | undefined): Grant | null => {
    const [body, mac] = (token ?? '').split('.');
    if (!body || !mac) return null;
    const expected = Buffer.from(sign(body));
    const given = Buffer.from(mac);
    if (expected.length !== given.length || !timingSafeEqual(expected, given)) return null;
    try {
      const grant = JSON.parse(Buffer.from(body, 'base64url').toString()) as Grant;
      return grant.exp > Date.now() && SAFE_KEY.test(grant.key) ? grant : null;
    } catch {
      return null;
    }
  };
  const fileFor = (key: string) => {
    if (!SAFE_KEY.test(key)) throw new Error(`refusing storage key ${key}`);
    return path.join(config.dir, ...key.split('/'));
  };
  const typeFile = (key: string) => `${fileFor(key)}.type`;
  const write = async (key: string, body: Buffer, type: string) => {
    await fs.mkdir(path.dirname(fileFor(key)), { recursive: true });
    await fs.writeFile(fileFor(key), body);
    await fs.writeFile(typeFile(key), type);
  };

  const storage: StorageService = {
    async presignPut(key, { contentType, size, expiresInSeconds }) {
      const exp = Date.now() + expiresInSeconds * 1000;
      return {
        url: issue({ op: 'put', key, type: contentType, size, exp }),
        headers: { 'content-type': contentType },
        expiresAt: new Date(exp),
      };
    },
    async presignGet(key, { fileName, expiresInSeconds, disposition, contentType }) {
      const exp = Date.now() + expiresInSeconds * 1000;
      return {
        url: issue({
          op: 'get',
          key,
          exp,
          disposition: contentDisposition(fileName, disposition),
          type: contentType,
        }),
        expiresAt: new Date(exp),
      };
    },
    async head(key) {
      try {
        const stat = await fs.stat(fileFor(key));
        return { size: stat.size, contentType: await fs.readFile(typeFile(key), 'utf8') };
      } catch {
        return null;
      }
    },
    async readRange(key, start, end) {
      const handle = await fs.open(fileFor(key));
      try {
        const buf = Buffer.alloc(end - start + 1);
        const { bytesRead } = await handle.read(buf, 0, buf.length, start);
        return buf.subarray(0, bytesRead);
      } finally {
        await handle.close();
      }
    },
    async stream(key) {
      return createReadStream(fileFor(key));
    },
    put: write,
    async copy(fromKey, toKey) {
      await fs.mkdir(path.dirname(fileFor(toKey)), { recursive: true });
      await fs.copyFile(fileFor(fromKey), fileFor(toKey));
      await fs.copyFile(typeFile(fromKey), typeFile(toKey));
    },
    async delete(key) {
      await fs.rm(fileFor(key), { force: true });
      await fs.rm(typeFile(key), { force: true });
    },
  };

  const routes: FastifyPluginAsync = async (app) => {
    // Raw bytes for uploads, scoped to these routes only
    app.addContentTypeParser(
      '*',
      { parseAs: 'buffer', bodyLimit: 11 * 1024 * 1024 },
      (_r, body, done) => done(null, body),
    );

    app.put<{ Querystring: { t?: string } }>(LOCAL_STORAGE_PATH, async (request, reply) => {
      const grant = verify(request.query.t);
      if (grant?.op !== 'put') return reply.code(403).send();
      const body = request.body as Buffer | undefined;
      // Same rules B2 enforces on a presigned PUT: the signed type and the exact size
      if (request.headers['content-type'] !== grant.type || body?.length !== grant.size) {
        return reply.code(403).send();
      }
      await write(grant.key, body, grant.type);
      return reply.code(200).send();
    });

    app.get<{ Querystring: { t?: string } }>(LOCAL_STORAGE_PATH, async (request, reply) => {
      const grant = verify(request.query.t);
      if (grant?.op !== 'get') return reply.code(403).send();
      const info = await storage.head(grant.key);
      if (!info) return reply.code(404).send();
      return reply
        .header('content-type', grant.type ?? info.contentType ?? 'application/octet-stream')
        .header('content-disposition', grant.disposition)
        .send(createReadStream(fileFor(grant.key)));
    });
  };

  return { storage, routes };
}
